In [1]:
import torch
import torch.nn.functional as F

e:\HocTap\ML\ContinualLearning\.venv\Lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [13]:
pred = torch.randn(1, 2, 3, 3, 3)


In [14]:
pred

tensor([[[[[-0.3666, -0.1789, -0.3015],
           [-1.1863,  0.8609, -0.9325],
           [ 0.6061, -0.2307,  1.0710]],

          [[-1.3074,  0.2537, -0.1385],
           [ 0.3581, -0.0613,  0.2460],
           [ 1.6468,  0.2739,  0.6683]],

          [[-0.2169,  1.2458, -0.5920],
           [ 0.1181,  0.5866,  0.1191],
           [ 0.4307,  0.2219,  0.0679]]],


         [[[-0.8369,  0.2369, -1.3818],
           [-1.2161,  0.5962,  1.5072],
           [ 1.5431, -0.1711, -1.8046]],

          [[ 0.5203,  1.4847, -1.3670],
           [ 0.5314, -0.0295,  0.4863],
           [ 0.8407,  1.8738, -1.5293]],

          [[-0.3530, -1.3376, -1.1226],
           [-0.2724,  0.5982, -0.6006],
           [ 0.8778, -1.4884,  0.4192]]]]])

In [15]:
pred_sigmoid = F.sigmoid(pred)

In [17]:
pred_sigmoid

tensor([[[[[0.4094, 0.4554, 0.4252],
           [0.2339, 0.7028, 0.2824],
           [0.6470, 0.4426, 0.7448]],

          [[0.2129, 0.5631, 0.4654],
           [0.5886, 0.4847, 0.5612],
           [0.8385, 0.5681, 0.6611]],

          [[0.4460, 0.7766, 0.3562],
           [0.5295, 0.6426, 0.5297],
           [0.6060, 0.5553, 0.5170]]],


         [[[0.3022, 0.5590, 0.2007],
           [0.2286, 0.6448, 0.8187],
           [0.8239, 0.4573, 0.1413]],

          [[0.6272, 0.8153, 0.2031],
           [0.6298, 0.4926, 0.6192],
           [0.6986, 0.8669, 0.1781]],

          [[0.4127, 0.2079, 0.2455],
           [0.4323, 0.6452, 0.3542],
           [0.7064, 0.1842, 0.6033]]]]])

In [18]:
pred_hard = pred_sigmoid > 0.5

In [20]:
pred_hard_post = pred_hard

In [23]:
pred1 = pred_hard_post[0, 0,:, :, :] 

In [24]:
preds = torch.where(pred1 > 0.5, 1., 0.)

In [25]:
preds

tensor([[[0., 0., 0.],
         [0., 1., 0.],
         [1., 0., 1.]],

        [[0., 1., 0.],
         [1., 0., 1.],
         [1., 1., 1.]],

        [[0., 1., 0.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [27]:
import numpy as np

# Ma trận đầu vào
input_matrix = np.array([[-0.3666, -0.1789, -0.3015],
                         [-1.1863,  0.8609, -0.9325],
                         [ 0.6061, -0.2307,  1.0710]])

# Hàm sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Tính toán sigmoid cho ma trận đầu vào
output_matrix = sigmoid(input_matrix)

print(output_matrix)


[[0.40936284 0.45539391 0.42519084]
 [0.23392133 0.70284866 0.28241779]
 [0.64705065 0.44257945 0.74478704]]
